# Generated by Django 4.2.8 on 2023-12-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=75, verbose_name="Nombre")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Usuario"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "password",
                    models.CharField(max_length=250, verbose_name="Contraseña"),
                ),
            ],
            options={
                "db_table": "user",
            },
        ),
    ]
